use crate::content::EntityBlueprint;

pub static ENTITY_BLUEPRINTS: &[EntityBlueprint] = &[
    EntityBlueprint {
        kind: "guide",
        display_name: "Guide",
        description: "Demo NPC; dialogue id \"guide\".",
        default_glyph: 'g',
        default_label: "Guide",
        dialogue_id: Some("guide"),
        world_item: None,
        is_container: false,
    },
    EntityBlueprint {
        kind: "healer",
        display_name: "Healer",
        description: "Simple tonic fetch quest (dialogue \"healer\").",
        default_glyph: 'h',
        default_label: "Healer",
        dialogue_id: Some("healer"),
        world_item: None,
        is_container: false,
    },
    EntityBlueprint {
        kind: "scholar",
        display_name: "Scholar",
        description: "Ring hand-in quest (dialogue \"scholar\").",
        default_glyph: 's',
        default_label: "Scholar",
        dialogue_id: Some("scholar"),
        world_item: None,
        is_container: false,
    },
    EntityBlueprint {
        kind: "merchant",
        display_name: "Merchant",
        description: "Flavor NPC (dialogue \"merchant\").",
        default_glyph: 'm',
        default_label: "Merchant",
        dialogue_id: Some("merchant"),
        world_item: None,
        is_container: false,
    },
    EntityBlueprint {
        kind: "prop",
        display_name: "Prop",
        description: "Set dressing; no dialogue hook.",
        default_glyph: '*',
        default_label: "Crate",
        dialogue_id: None,
        world_item: None,
        is_container: false,
    },
    EntityBlueprint {
        kind: "health_tonic_drop",
        display_name: "Health tonic",
        description: "World pickup for healer quest.",
        default_glyph: '!',
        default_label: "Tonic",
        dialogue_id: None,
        world_item: Some("health_tonic"),
        is_container: false,
    },
    EntityBlueprint {
        kind: "brass_ring_drop",
        display_name: "Brass ring",
        description: "World pickup for scholar quest.",
        default_glyph: '=',
        default_label: "Ring",
        dialogue_id: None,
        world_item: Some("brass_ring"),
        is_container: false,
    },
    EntityBlueprint {
        kind: "wooden_chest",
        display_name: "Wooden chest",
        description: "Storage; press E nearby to open transfer.",
        default_glyph: '□',
        default_label: "Chest",
        dialogue_id: None,
        world_item: None,
        is_container: true,
    },
];
